### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by 1015356144** [Flame-Chasers/TBPS-CLIP#3]
when I use the "# OMP_NUM_THREADS=1 \
# CUDA_VISIBLE_DEVICES=0,1,2,3 \
# torchrun --rdzv_id=3 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 --nnodes=1 --nproc_per_node=4 \
# main.py --simplified" command, I get the Segmentation fault, how could I solve this problem. I just set the path in the s.config.yaml file and don't change code else
![Uploading 1584659047.png…]()

**Comment by byougert** [comment]
Hi @1015356144 ,
Thx for your interest in our work.

I understand that you are experiencing a segmentation fault error, but the uploaded image appears to be broken. 
Unfortunately, without the detailed error information, it becomes challenging to identify the root cause of the issue.

Could you please provide the error message again?
